management:
  endpoints:
    web:
      exposure:
        include: "*"
    shutdown:
      enabled: true

eureka:
  instance:
    nonSecurePortEnabled: false
    securePortEnabled: true

spring:
  jmx:
    enabled: true

logging:
  level:
    root: INFO