spring:
  cloud:
    gateway:
      httpclient:
        ssl:
          useInsecureTrustManager: true
      routes:
        - id: greeting-external
          uri: https://${GREETING_EXTERNAL_SERVICE}/
          predicates:
            - Path=/greeting-external/**
        - id: greeting
          uri: https://${GREETING_SERVICE}/
          predicates:
            - Path=/greeting/**