spring:
  cloud:
    gateway:
      httpclient:
        ssl:
          useInsecureTrustManager: true
      routes:
        - id: greeting-external
          uri: lb:https://greeting-external-service
          predicates:
            - Path=/greeting-external/**
        - id: greeting
          uri: lb:https://greeting-service
          predicates:
            - Path=/greeting/**

azure:
  keyvault:
    jca:
      overrideTrustManagerFactory: true
      disableHostnameVerification: true