spring:
  cloud:
    gateway:
      httpclient:
        ssl:
          useInsecureTrustManager: true
      routes:
        - id: greeting-external
          uri: lb:https://greeting-external-service
          predicates:
            - Path=/greeting-external/**
        - id: greeting
          uri: lb:https://greeting-service
          predicates:
            - Path=/greeting/**

server:
  ssl:
    enabled: true
    key-store-type: AzureKeyVault
    key-alias: ${SERVER_SSL_CERTIFICATE_NAME}

azure:
  keyvault:
    uri: ${KEY_VAULT_URI}
    jca:
      overrideTrustManagerFactory: true
      disableHostnameVerification: true